# Generated by Django 2.1.4 on 2018-12-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('credit_points', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
