# Generated by Django 2.1.4 on 2018-12-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('credit_points', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.EmailField(default=None, max_length=254)),
                ('weight', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicfunc.Participant')),
            ],
        ),
    ]
