# Generated by Django 2.1.4 on 2018-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicfunc', '0002_transferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='donor',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
