# Generated by Django 2.1.4 on 2018-12-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicfunc', '0003_transferhistory_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicfunc.Participant'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='target',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
