# Generated by Django 2.1.4 on 2018-12-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicfunc', '0004_auto_20181221_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='credit_points',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='basicfunc.Participant'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='basicfunc.Participant'),
        ),
    ]
